### ISSUE TITLE
Bandwidth always reported as 0

### ISSUE THREAD

**Issue by jloh** [fcambus/logswan#14] opened 2018-10-14 10:30 UTC
First off, thanks for the amazing tool! `logswan` is fantastic.

For some reason, bytes is always returned as `0` for me, I'm not 100% sure whether its my log format or something else. Heres what I've got configured in Nginx:

```
log_format swanlog '$remote_addr - $remote_user [$time_local] "$request" $status $body_bytes_sent $request_length $request_time "$http_referer" "$http_user_agent"';
```

And the output from a sample run:

```json
{
   "date": "2018-10-14 21:24:41",
   "generator": "Logswan 2.0.2",
   "file_name": "test.log",
   "file_size": 1018,
   "processed_lines": 10,
   "invalid_lines": 0,
   "bandwidth": 0,
   "runtime": 0.010923858999999999,
<snip>
```

Heres the log lines I'm running it against (with some info redacted)

```
127.0.0.1 - - [13/Oct/2018:06:25:13 +1100] "GET /some_path HTTP/2.0" 200 498 21 0.001 "<redacted>" "<redacted>"
127.0.0.1 - - [13/Oct/2018:06:25:14 +1100] "GET /path_2 HTTP/1.0" 200 483 81 0.000 "<redaced>" "<redacted>"
```

The IPs are both IPv6/IPv4 but they parse fine. HTTP2/0 doesn't seem to parse yet either weirdly.

I'm running this on Ubuntu 16.04 with the latest (Swanlog 2.0.2).

**Comment by fcambus** [comment] 2018-10-14 18:42
Hi James,

Thanks for your reports. As it turns out, the 2.0.2 release hasn't been the best to say the least...

I pushed a fix to enable HTTP/2.0 parsing, and I will push a fix soon for the bandwidth counting issue, it's a regression introduced in 2.0.2.

**Comment by jloh** [comment] 2018-10-15 02:17
@fcambus I've pulled master and rebuilt and everything is working perfectly now, thanks for your help!

**Comment by fcambus** [comment] 2018-10-15 11:24
I just tagged 2.0.3, fixing the issue and mentioned you in the ChangeLog, thanks again for reporting this and testing the fixes!

**Closed as completed by fcambus** 2018-10-15 11:24 UTC
